[package]
name = "floppabot"
version = "0.1.0"
edition = "2021"
publish = false

[lib]

[dependencies]
shuttle-service = { version = "0.9.0", features = ["bot-serenity"] }
anyhow = "1.0.68"
serenity = "0.11.5"
shuttle-secrets = "0.9.0"
tracing = "0.1.37"
urlencoding = "2.1.2"
reqwest-eventsource = "0.4.0"
poise = "0.5.2"