[package]
name = "floppabot"
version = "0.1.0"
edition = "2021"
publish = false

[lib]

[dependencies]
shuttle-service = { version = "0.8.0", features = ["bot-serenity"] }
anyhow = "1.0.68"
serenity = "0.11.5"
shuttle-secrets = "0.8.0"
tracing = "0.1.37"
